/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AMenu: typeof import('ant-design-vue/es')['Menu']
    Code: typeof import('./src/components/code.vue')['default']
    Main: typeof import('./src/components/main/index.vue')['default']
    Nav: typeof import('./src/components/nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test_gradually_appear: typeof import('./src/components/css/test_gradually_appear.vue')['default']
    Text_adaptation_texture: typeof import('./src/components/css/text_adaptation_texture.vue')['default']
    Text_blend_spread: typeof import('./src/components/css/text_blend_spread.vue')['default']
  }
}
