/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACollapse: typeof import('ant-design-vue/es')['Collapse']
    ACollapsePanel: typeof import('ant-design-vue/es')['CollapsePanel']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    Border_repeat_gradient: typeof import('./src/components/css/border_repeat_gradient.vue')['default']
    Code: typeof import('./src/components/content/code.vue')['default']
    Handle: typeof import('./src/components/common/header/handle.vue')['default']
    Header: typeof import('./src/components/common/header/index.vue')['default']
    Knowledge: typeof import('./src/components/common/header/knowledge.vue')['default']
    Knowledge_point: typeof import('./src/components/popup/knowledge_point.vue')['default']
    Nav: typeof import('./src/components/common/nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting_config: typeof import('./src/components/popup/setting_config.vue')['default']
    Test_gradually_appear: typeof import('./src/components/css/test_gradually_appear.vue')['default']
    Text_blend_spread: typeof import('./src/components/css/text_blend_spread.vue')['default']
    Theme: typeof import('./src/components/popup/setting/theme.vue')['default']
  }
}
